### PR TITLE
fixed url_for build for post_logout_redirect_uris

### PR DESCRIPTION
**Pull request by infohash**
Addresses #116 

Fixed url_for build error of post_logout_redirect_urls when using dynamic client registration

### CODE REVIEW

**Comment by zamzterz** [comment]
Thanks for the great contribution! 👏 

As you point out in #116 the default value is incorrectly calculated when `post_logout_redirect_uris` is already set here:
https://github.com/zamzterz/Flask-pyoidc/blob/b0058c0724f35d6999322d0a584003185c3189d9/src/flask_pyoidc/flask_pyoidc.py#L95-L97

I think it would be more robust to fix that instead, i.e. `default_post_logout_redirect_uris()` should only be called when the `get()` returns `None`.
That way, the `BuildError` is not "silently" swallowed, hiding possible misconfiguration. WDYT?

**Comment by infohash** [comment]
Agreed. If get returns None then only `default_post_logout_redirect_uris()` will be raised. It will raise an exception if the logout endpoint is mounted at custom endpoint and user doesn't provide it as an argument.

**Comment by zamzterz** [comment]
Sounds good then! Would you be able to update this PR to reflect that change instead?

**Comment by zamzterz** [comment]
@infohash Thanks for the swift changes. 👍 

I just added some minor formatting changes, and will release a new version with this fix in just a bit.

**Pull request merged**
