### PR TITLE
Update docs in Quickstart and Configuration.

### PR DESCRIPTION
**Pull request by zamzterz**
* Simplify code examples.
* Move "Client credentials flow" docs from Configuration to Quickstart.
* Update year in docs copyright notice.

### CODE REVIEW

**Comment by infohash** [comment]
```python
provider_config = ProviderConfiguration(client_metadata=client_metadata, [provider_configuration])

provider_config = ProviderConfiguration(client_registration_info=client_registration_info, [provider_configuration])
```

This looks confusing to the reader because it doesn't specify what keyword has to be provided to provide `provider_configuration`. The keyword can be either `issuer` or `provider_metadata`.

```python
provider_config = ProviderConfiguration(issuer='https://idp.example.com', [client configuration])
provider_config = ProviderConfiguration(provider_metadata=provider_metadata, [client configuration])
```

Same as above. `client_configuration` can be provided with `client_metadata` and `client_registration_info`.

It should be self descriptive so that the user can understand arguments just by looking at first line. Most users copy paste these lines so keyword arguments should be syntactically correct.

**Comment by zamzterz** [comment]
I don't think putting together the two examples from your excerpts is too tricky.
Mainly I found, after looking at the rendered docs, that the configuration code blocks were long and even though well-commented, it still required reading through it to pick the correct configuration combination.

**Comment by infohash** [comment]
Can  you add quickstart on PYPI? The page looks too empty.

**Comment by zamzterz** [comment]
Great idea, fixed in #125 👍

**Pull request merged**
